[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "seadrop/=lib/seadrop/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "utility-contracts/=lib/seadrop/lib/utility-contracts/src/"
]

# Solidity compiler settings
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200
via_ir = true

# Network configurations
[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Gas settings
[profile.default.fuzz]
runs = 1000

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 1_000, fail_on_revert = false }